# Generated by Django 4.1.7 on 2023-03-31 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_remove_company_users_alter_company_author'),
        ('projects', '0002_alter_project_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('date_sprint', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы над задачей')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('on_hold', 'OnHold'), ('back_log', 'BackLog'), ('to_estimate', 'ToEstimate'), ('to_do', 'ToDo'), ('in_progress', 'InProgress'), ('dev', 'Dev'), ('test', 'Test'), ('pause', 'Пауза'), ('solved', 'Решена')], default='new', max_length=300, verbose_name='Статус задачи')),
                ('time_tracker', models.IntegerField(default=0, verbose_name='Число затреканных часов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Компания')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_executor', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tasks/%Y/%m/%d')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task')),
            ],
        ),
    ]
