# Generated by Django 4.1.7 on 2023-03-31 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterModelOptions(
            name='taskfiles',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='taskfiles',
            name='file',
            field=models.FileField(upload_to='tasks/%Y/%m/%d', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='taskfiles',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='Задача'),
        ),
    ]
