# Generated by Django 4.1.7 on 2023-03-30 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение компании')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'permissions': (('can_update_company_permission', 'Право на обновление данных компании'), ('can_delete_company_permission', 'Право на удаление данных компании')),
            },
        ),
    ]
