# Generated by Django 4.1.7 on 2023-03-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_users_alter_company_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название компании'),
        ),
    ]
